### ISSUE TITLE
stringsToJson 没有定义

### ISSUE THREAD

**Issue by enjoydiy** [beego/admin#42]
2015/11/27 15:53:14 [template.go:153] [D] parse template err: easyui/rbac/access
tonode.tpl template: easyui/rbac/accesstonode.tpl:4: function "stringsToJson" no
t defined
2015/11/27 15:53:14 [template.go:153] [D] parse template err: easyui/rbac/node.t
pl template: easyui/rbac/node.tpl:3: function "stringsToJson" not defined
2015/11/27 15:53:14 [asm_amd64.s:1696] [I] http server Running on :8080

stringsToJson这个函数哪里可以找到？

**Comment by lchjczw** [comment]
我也是遇到相同的问题呢

**Comment by astaxie** [comment]
更新到beego1.6的问题，我已经bee fix了admin，再重试一下

**Comment by zhouya2010** [comment]
2017/05/26 14:01:06 [E] [template.go:174] parse template err: easyui/rbac/accesstonode.tpl template: easyui/rbac/accesstonode.tpl:4: function "stringsToJson" not defined
2017/05/26 14:01:06 [E] [template.go:174] parse template err: easyui/rbac/node.tpl template: easyui/rbac/node.tpl:3: function "stringsToJson" not defined

还是报错？
