### ISSUE TITLE
运行出panic错误，真是醉了

### ISSUE THREAD

**Issue by funnyblack** [beego/admin#46]
按照例子完成之后，运行出来如下的错误，跪求大神告诉我应该如何找问题点在哪里：

panic: read the content error: "", should key = val

goroutine 1 [running]:
panic(0xa79fa0, 0xc0820035d0)
        D:/Go/src/runtime/panic.go:481 +0x3f4
github.com/astaxie/beego.init.3()
        D:/Go/sources/src/github.com/astaxie/beego/config.go:189 +0x86b
github.com/astaxie/beego.init()
        D:/Go/sources/src/github.com/astaxie/beego/tree.go:580 +0x78d
hello/controllers.init()
        D:/Go/sources/src/hello/controllers/default.go:15 +0x42
hello/routers.init()
        D:/Go/sources/src/hello/routers/router.go:13 +0x42
main.init()
        D:/Go/sources/src/hello/main.go:10 +0x42

**Comment by chengshihard** [comment]
我也遇到了这个问题   楼主怎么解决的

**Comment by funnyblack** [comment]
我记得当时是配置文件配错了，但是太久，已经忘了具体是哪一条的问题，不过按照谢老师的步骤最后是可以成功的，go的版本最好也新一点，老版本运行好像也会有问题...
